services:
  devcontainer:
    container_name: devcontainer
    image: mcr.microsoft.com/devcontainers/base:debian
    volumes:
      - ../..:/workspaces:cached
      - nix:/nix
    network_mode: service:db
    command: sleep infinity

  app:
    container_name: app
    image: kennycallado/q-app-php:latest
    pull_policy: always
    network_mode: service:db
    environment:
      ENVIRONMENT: development
      DATABASE_URL: http://localhost:8000/sql
      AUTH_URL: http://localhost:9000/auth
    volumes:
      - ..:/var/www/html

  db:
    container_name: surrealdb
    image: kennycallado/q-api-store-demo:latest
    pull_policy: always
    command:
      - -A
      - --no-banner
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    container_name: super
    image: kennycallado/q-api-super:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: service:db
    environment:
      DB_HOST: 'localhost:8000'

  auth:
    container_name: auth
    image: kennycallado/q-api-auth:latest
    pull_policy: always
    restart: unless-stopped
    network_mode: service:db
    environment:
      ROCKET_PORT: 9000
      ROCKET_DATABASES: '{store={host="localhost", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: 'xdOXN1pEDSi3TYupqi7jOtXwaa3rOfClDPuW3HzMdkU='

volumes:
  nix:
