# WARNING: Currently, this file is not used.
#
# Description: This file is used to build the devcontainer image
# installing some tools that are useful for development.
# Version: 0.1
FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
  apt-get -y install --no-install-recommends \
  ripgrep \
  jq

# Clean up apt
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
