FROM ghcr.io/xtruder/nix-devcontainer:v1

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
  apt-get -y install --no-install-recommends \
  fd

# Clean up apt
RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

VOLUME /nix
