FROM ghcr.io/xtruder/nix-devcontainer:v1

VOLUME /nix

# Description: This file is used to build the devcontainer image
# installing some tools that are useful for development.

# FROM mcr.microsoft.com/devcontainers/base:debian

# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
#   apt-get -y install --no-install-recommends \
#   php-cli \
#   php-curl \
#   php-json \
#   php-mbstring \
#   php-xml \
#   php-pcov \
#   composer \
#   ripgrep

# # Clean up apt
# RUN apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
